/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackBtn: typeof import('./src/components/backBtn.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElLin: typeof import('element-plus/es')['ElLin']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuI: typeof import('element-plus/es')['ElMenuI']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    PortTest: typeof import('./src/components/PortTest.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
