/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackBtn: typeof import('./components/backBtn.vue')['default']
    ChartToolbar: typeof import('./components/charts/ChartToolbar.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElList: typeof import('element-plus/es')['ElList']
    ElListItem: typeof import('element-plus/es')['ElListItem']
    ElListItem__actions: typeof import('element-plus/es')['ElListItem__actions']
    ElListItem__content: typeof import('element-plus/es')['ElListItem__content']
    ElLoading: typeof import('element-plus/es')['ElLoading']
    ElMain: typeof import('element-plus/es')['ElMain']
    FileImporter: typeof import('./components/common/FileImporter.vue')['default']
    MainLayout: typeof import('./components/layout/MainLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SerialConfigForm: typeof import('./components/serial/SerialConfigForm.vue')['default']
    SerialSidebar: typeof import('./components/layout/SerialSidebar.vue')['default']
    TemperatureChart: typeof import('./components/charts/TemperatureChart.vue')['default']
    TempThresholdForm: typeof import('./components/serial/TempThresholdForm.vue')['default']
    TimeRangeSelector: typeof import('./components/common/TimeRangeSelector.vue')['default']
    Toolbar: typeof import('./components/layout/Toolbar.vue')['default']
  }
}
